config/routes.rb
Rails.application.routes.draw do

  get 'welcome/about', to: "welcome#about"

  get "/lessons/search", to: 'lessons#search', as: 'lessons_search'
  devise_for :users

  resources :profiles

  resources :lessons do
    member do 
      get 'add_student'
      get 'roster'
      get 'map', to: 'lessons#map'
    end
    resources :comments
  end

  

  
  resources :charges
  
  
  root "welcome#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	
	geocoded_by :address
	after_validation :geocode
	has_many :students, class_name: "User", foreign_key: 'user_id'
	
	belongs_to :host, class_name: "User"
	has_many :comments
	has_and_belongs_to_many :users


	def self.search(query)
  		where("name ILIKE ? or category ILIKE ? or address ILIKE ?", "%#{query}%", "%#{query}%", "%#{query}%") 
	end


end
 

app/models/place.rb
class Place < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :lessons
  
  has_one :profile
  # :role
  # user == 0
  # admin == 1
  # rails generate migration AddRoleToUser Role:integer 
  # Rake db:migrate
  enum role: [:user, :admin, :editor]
  # user.update role: 1
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500 #= $5

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @lesson = Lesson.find(params[:lesson_id])
        @comment = @lesson.comments.create(comment_params)
        redirect_to lesson_path(@lesson)
    end
    
    def destroy
        @lesson = Lesson.find(params[:lesson_id])
        @comment = @lesson.comments.find(params[:id])
        @comment.destroy
        redirect_to lesson_path(@lesson)
    end
    
    def edit
        @lesson = Lesson.find(params[:lesson_id])
		@comment = Comment.find(params[:id])
    end
    
    private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
	

	before_action :authenticate_user!
	# before_action :authorize_admin!, only: [:new, :destroy]

	# before_action :authorize_admin!, only: [:new, :create, :destroy]
	# before_action :authorize_editor_or_admin!, only: [:edit, :update]

	def index
		@lessons = Lesson.all
		@geojson = Array.new

		@lessons.each do |lesson|
			@geojson << {
				type: 'Feature',
				geometry:{
					type: 'Point',
					coordinates: [lesson.longitude, lesson.latitude]
					},
					properties: {
						name: lesson.name,
						address: lesson.address,
						:'marker-color' => '#00607d',
						:'marker-symbol' => 'circle',
						:'marker-size' => 'medium'
					}
				}
			end
			respond_to do |format|
				format.html
				format.json { render json: @geojson } 
			end
		end

		def search
			@lessons = Lesson.search(params[:q])
			render :index
		end

		def new
			@lesson = Lesson.new
		end

		def create
			@lesson = current_user.lessons.build(lesson_params)
			@lesson.host = current_user

			if @lesson.save
				redirect_to @lesson
			else
				render "new"
			end
		end

		def edit
			@lesson = Lesson.find(params[:id])
			unless current_user == @lesson.host
				redirect_to :root, alert: "Only the host can edit the workshop information"
			end
		end

		def update
			@lesson = Lesson.find(params[:id])

			if @lesson.update(lesson_params)
				redirect_to @lesson 
			else
				render 'edit'
			end
		end

		def destroy
			@lesson = Lesson.find(params[:id])
			unless current_user == @lesson.host
				redirect_to :root, alert: "Only the host can edit the workshop information"
			end
			@lesson.destroy
		end

	def show
		@lesson = Lesson.find(params[:id])
		@comment = @lesson.comments.build
		@all_comments = @lesson.comments.reject(&:new_record?)
		@profile = Profile.find(@lesson.host_id)
	end

	def map
		@lesson = Lesson.find(params[:id])
		@geojson = Array.new

  		@geojson << {
  			type: 'Feature',
  			geometry:{
  				type: 'Point',
  				coordinates: [@lesson.longitude, @lesson.latitude]
  				},
  				properties: {
  					name: @lesson.name,
  					address: @lesson.address,
  					:'marker-color' => '#00607d',
      				:'marker-symbol' => 'circle',
     				:'marker-size' => 'medium'
  					}
  				}

		respond_to do |format|
			format.html
			format.json { render json: @geojson } 
		end
	end

	def new
		@lesson = Lesson.new
	end

	def create
		@lesson = current_user.lessons.build(lesson_params)
		@lesson.host = current_user

		if @lesson.save
			redirect_to @lesson
		end
	end

	def add_student
		@lesson = Lesson.find(params[:id])
		@lesson.users << current_user
		redirect_to roster_lesson_path(@lesson)
	end

	def roster
		@lesson = Lesson.find(params[:id])
	end

	private 
	def lesson_params
		params.require(:lesson).permit(:StartTime, :EndTIme, :address,
			:category, :name, :price, :capacity, :description, :language, :user_id)
	end

	def place_params
		params.require(:place).permit(:name, :address)
	end

	def has_permission(lesson)
		current_user == lesson.host 
	end

	def authorize_admin!
		unless current_user.admin?
			redirect_to :root, alert: "You can't do that!"
		end
	end
	
	def authorize_editor_or_admin!
		if current_user.admin? || current_user.editor?
		else
			redirect_to :root, alert: "You can't do that!"
		end
	end


end

app/controllers/profiles_controller.rb
	class ProfilesController < ApplicationController

	def new
		@profile = Profile.new
	end

	def show
		@profile = Profile.find(params[:id])
		@user = User.find(@profile.user)
	end


	def edit
		@profile = Profile.find(params[:id])
	end

	def update
		@profile = Profile.find(params[:id])

		if @profile.update(profile_params)
		redirect_to @profile 
		else
		render 'edit'
		end
	end

	def create
		@profile = Profile.new(profile_params)
		@profile.user = current_user

		if @profile.save
			redirect_to @profile
		else
			render 'new'
		end
	end

	private

	def profile_params
		params.require(:profile).permit(:name, :photo, :description, :base, :education, :interests)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		random_lesson_ids = (1...Lesson.count).to_a.shuffle.take(4)
		@featured_lessons = []
		random_lesson_ids.each do |id|
			@featured_lessons << Lesson.find(id)
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

# # module AnimalHelper
# #         def can_user_create_animal?
# #             user_signed_in && current_user.admin?
# #         end
# #     end
#  module AnimalHelper
# #         def can_user_edit_animal?
# #             user_signed_in && (current_user.admin? || current_user.editor)
# #         end
# #     end
#  module AnimalHelper
# #         def can_user_destory_animal?
# #             user_signed_in && current_user.admin?
# #         end
# #     end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
    def has_permission(lesson)
        current_user == lesson.host || current_user.role == admin
    end

    def can_create_animal?
    	user_signed_in? && current_user.admin?
    end
    def can_edit_animal?
    	user_signed_in? && (current_user.admin? || 
    		current_user.admin?)
    end
    def can_destroy_animal?
    	user_signed_in? && current_user.admin?
    end
end

app/views/charges/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %> 
</p>


<p>
  <%= link_to 'Edit Comment', edit_lesson_comment_path(comment.lesson, comment) %>
</p>


<p>
  <%= link_to 'Destroy Comment', [comment.lesson, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for ([@lesson, @comment]) do |f| %>
    <p>
        <%= f.label :commenter %><br>
        <%= f.text_field :commenter %>
    </p>
    
    <p>
        <%= f.label :body %><br>
        <%= f.text_field :body %>
    </p>
    
    <p>
        <%= f.submit 'Submit', :class => "btn btn-success" %>
    </p>
<%end%>

<% link_to 'Back', lessons_path %>

app/views/comments/edit.html.erb
<h2>Edit your comment:</h2>

<%= render 'form' %>

app/views/comments/show.html.erb
<h2>Add a comment:</h2>

<%= render 'form" %>'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Workshop</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand", href="/">Workshop</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/welcome/about">About</a>
                    </li>
                    <li>
                        <a href="/lessons">Find A Workshop</a>
                    </li>
                    <li>
                        <a href="/lessons/new">Host A Workshop</a>
                    </li>


                    <% if user_signed_in? %>
                    <% if Profile.find_by_id(current_user.id) %>
                    <li><%=link_to "Your Profile", profile_path(current_user)%></li>
                    <li><%= link_to 'Edit profile', edit_profile_path(current_user), :class => 'navbar-link' %></li>
                    <% else %>
                    <li><%=link_to "Create Your Profile", new_profile_path %></li>
                    <% end %>
                    
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                    <li><a>Logged in as <%= current_user.email %></a></li>

                    <% else %>
                        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
                    <% end %>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
    <p class="alert alert-danger padding-top"><%= alert %></p>
    <% end %>

    <%= yield %>


    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; iXperience 2015</p>
            </div>
        </div>
    </footer>
</body>
</html>

app/views/lessons/_form.html.erb
<div class="form">
    <%= form_for @lesson do |f| %>

    <p>
        <%= f.label "Workshop name" %><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label "Image URL" %><br>
        <%= f.text_field :image %>
    </p>
    <p>
        <%= f.label :category %><br>
        <%= f.text_field :category %>
    </p>

    <p>
        <%= f.label "Start Time"  %><br>
        <%= f.text_field :StartTime %>
    </p>

    <p>
        <%= f.label "End Time" %><br>
        <%= f.text_field :EndTime %>
    </p>

    <p>
        <%= f.label :price %><br>
        <%= f.text_field :price %>
    </p>

    <p>
        <%= f.label :capacity %><br>
        <%= f.text_field :capacity %>
    </p>

    <p>
        <%= f.label :description %><br>
        <%= f.text_field :description %>
    </p>

    <p>
        <%= f.label :langauge %><br>
        <%= f.text_field :langauge %>
    </p>



    <p>
        <%= f.label :address %><br>
        <%= f.text_field :address %>
    </p>

    <p><%= f.submit 'Submit', :class => "btn btn-success" %></p>

    <% end %>
</div>

app/views/lessons/_roster.html.erb
<p>Users in this workshop:</br>
	<% @lesson.users.each do |student| %>
		<%= link_to student.profile.name, profile_path(student) %> </br>
	<% end %>
</p>

app/views/lessons/edit.html.erb
<div class="container">

	<h1> Edit Workshop </h1>

	<%= render 'form' %>

	<%= link_to 'Delete This Workshop', lesson_path(@lesson),
	  method: :delete,
	  data: {confirm: 'Are you sure you want to delete this workshop?'} 
	%>


	<%= link_to 'Back to Lessons', @lesson %>
</div>

app/views/lessons/index.html.erb
<!-- Page Content -->
<div class="container">
    <!-- /.container -->
    
    <div class="index_page">
        <h1>All workshops</h1>
        <div class="row">
            <div class="col-md-3">
                <p class="lead">Search for a workshop</p>
                <div class="search_bar_index">
                    <%= form_tag lessons_search_path, method: :get do %>
                        <%= text_field_tag :q, params[:q]  %>
                        <%= submit_tag "Search" %>
                    <% end %>
                </div>
            </div>

            <!-- Right -->
            <div class="col-md-9">

             <!-- Carousel -->
             <div class="row carousel-holder">
                <div class="col-md-12">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">.
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="slide-image" src="http://i.imgur.com/pP5bgTE.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="http://i.imgur.com/bj4yheB.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="http://i.imgur.com/96ha6YF.jpg" alt="">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>
            </div>
            <!-- row -->
            <div class="row">
            <% @lessons.each do |lesson| %>
                 <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="<%=lesson.image%>" alt="img">
                        <div class="caption">
                            <h4 class="pull-right">$<%=lesson.price%></h4>
                            <h4><%=link_to lesson.name, lesson_path(lesson)%></h4>
                            <p><%=lesson.description%></p>
                        </div>
                        <div class="ratings">
                            <p class="pull-right">15 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                            </p>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>
</div>
</div>

app/views/lessons/new.html.erb
<div class="container">
	<div class ="new"
		<h1>New Workshop</h1>
	</div>	
		<%= render 'form' %>


</div>

app/views/lessons/roster.html.erb
<div class="container">


<p>Users in this workshop:</br>
	<% @lesson.users.each do |student| %>
		<%= link_to student.profile.name, profile_path(student) %> </br>
	<% end %>
</p>

</div>

app/views/lessons/show.html.erb
			<!-- Page Content -->
		<div class="container">


			<div class="show_page">
				<div class="row">
					<!-- left -->
					<div class="col-md-3">
						<p class="lead">Shop Name</p>
						<div class="search_bar_show">
							<%= form_tag lessons_search_path, method: :get do |f| %>
							<%= text_field :q, params[:q]  %>
							<%= submit_tag "Search" %>
							<% end %>
						</div>

					</div>

					<div class="col-md-9">
						<!-- right -->
						<!-- map -->
						<div class="thumbnail">
							<img class="img-responsive" src="<%=@lesson.image%>" alt="">
							<!-- /map -->
							<!-- details -->

                    <div class="caption-full">
                        <h4 class="pull-right">$<%=@lesson.price%></h4>
                        <h4><a href="#"><%= @lesson.name %></a>, 
                            Hosted by: <%= link_to @profile.name, profile_path(@profile)%>.</h4> 
                        <p>
	                        <% if current_user == @lesson.host %>
							    <%= link_to "Edit workshop details", edit_lesson_path %> | 
							    <%= link_to 'Destroy', lesson_path(@lesson),
											method: :delete, 
											data: { confirm: 'Are you sure?' } %> | 
							<% else %>
								<% if @lesson.users.size >= @lesson.capacity %>
									<strong>This workshop is full!</strong>
								<% else %>
									<%= link_to "Join workshop", add_student_lesson_path(@lesson) %>
								<% end %>
							<% end %>
							<%= link_to "See registered roster", roster_lesson_path(@lesson) %>
						</p>
                       	<p>This workshop will be from <%=@lesson.StartTime%> to <%=@lesson.EndTime%> at <%=@lesson.address%>.</p>
                        <p><%= @lesson.description %></p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">3 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star-empty"></span>
                            4.0 stars
                        </p>
                    </div>
                </div>
							<!-- /details -->
							<div class ="map">
								<!-- <body> -->
								<div id='map'></div>
								<script>
									L.mapbox.accessToken = 'pk.eyJ1IjoicmljaGFyZGxpbjMiLCJhIjoiOTM3NmRhZGI0ODY3ZWNiNTYwMjFhZjNiZDVjMzVmNDkifQ.AiyM9lt0c30Ktp_xyu3z3Q';
									var map = L.mapbox.map('map', 'mapbox.streets')
									.setView([-33.9253, 18.4239], 12);
									// var jsonURL = "/lessons/" + "<%= escape_javascript(params[:id]) %>" + "/map.json";
									var myLessons = L.mapbox.featureLayer()
									.loadURL("<%= escape_javascript(map_lesson_path(@lesson, :format => :json))%>")
									.addTo(map);
								</script>
	<!-- </body> -->
	<!-- </html> -->
<!-- details -->
<!-- comments -->
<div class="comments">
	<div class="well">
		<%= render '/comments/form' %>
		<div class="text-right">
		</div>
		<% @all_comments.each do |comment| %>
		<hr>
		<div class="row">
			<div class="col-md-12">
				<span class="glyphicon glyphicon-star"></span>
				<span class="glyphicon glyphicon-star"></span>
				<span class="glyphicon glyphicon-star"></span>
				<span class="glyphicon glyphicon-star"></span>
				<span class="glyphicon glyphicon-star-empty"></span>
				<p><%=comment.commenter%></p>
				<span class="pull-right">Posted on <%=comment.created_at%></span>
				<p><%=comment.body%></p>
			</div>
		</div>
		<% end %>
	</div>
</div>
<!-- /comments -->

app/views/profiles/_form.html.erb
<div class="profile">
    <%= form_for (@profile) do |f| %>
        <p>
            <%= f.label "Name" %><br>
            <%= f.text_field :name %>
        </p>
        
        <p>
            <%= f.label "Photo URL" %><br>
            <%= f.text_field :photo %>
        </p>

        <p>
            <%= f.label "Home base" %><br>
            <%= f.text_field :base %>
        </p>
        
        <p>
            <%= f.label "Description" %><br>
            <%= f.text_field :description %>
        </p>

        <p>
            <%= f.label "Education" %><br>
            <%= f.text_field :education %>
        </p>

        <p>
            <%= f.label "Interests" %><br>
            <%= f.text_field :interests %>
        </p>

        <p>
            <%= f.submit 'Submit', :class => "btn btn-success" %>
        </p>
    <%end%>

    <% link_to 'Back', lessons_path %>
</div>

app/views/profiles/edit.html.erb
<div class= "profile_edit">
	<div class= "container">
		<div class="col-md-6">
			<%= render "form" %>
		</div>

		<div class="col-md-6">
			<h1>Example Profile</h1>

			<p>Name: Robert Lee</p>
			<p>Photo URL: https://www.petfinder.com/wp-content/uploads/2012/11/99233806-bringing-home-new-cat-632x475.jpg</p>
			<p>Home Base: Providence RI</p>
			<p>Description:</br>
				I enjoy playing 4 chord songs on guitar, long walks on the beach and making babies smile.</p>
				<p>Education:</br>
					Chinese International School '12, Brown University '17 (Urban Studies)</p>
					<p>Interests:</br>
						I love arts and crafts, 
					</p>
				</div>
			</div>
		</div>

app/views/profiles/new.html.erb
<div class= "container">
	<div class= "profile_title">
		<h1> Create your profile!</h1>
	</div>
	<%= render "form" %>
</div>

app/views/profiles/show.html.erb
<div class="container">
	<div class="profile_show">
		<h1><%=@profile.name%>'s profile</h1>
		<% if @profile.user_id == current_user %>
			<%= link_to "edit your profile", edit_profile_path(@profile) %>
		<% end %>
		</br>
		<% if @profile.photo %>
			<img src="<%=@profile.photo%>">
		<% end %>
			<% if @profile.description %>
				<h2>Description</h2>
				<p><%=@profile.description%></p>
			<% end %>

			<% if @profile.base %>
				<h2>Based in:</h2>
				<p><%=@profile.base%></p>
			<% end %>

			<% if @profile.education %>
				<h2>Education</h2>
				<p><%=@profile.education%></p>
			<% end %>

			<% if @profile.interests %>
				<h2>Interests</h2>
				<p><%=@profile.interests%></p>
			<% end %>
		<h2>Contact me at:</h2>
		<p><%=@user.email%></p>
	</div>
</div>

app/views/welcome/about.html.erb
    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1 class="intro_heading_text">Workshop</h1>
                        <h3 class="intro_heading_subtext">Let's learn from each other</h3>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

    <a  name="services"></a>   
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">The Problem</h2>
                    <p class="lead">From Hong Kong, to New York City, to the Cape Townian Township Khayelitsha, schools face the same growing obstacle: over-regulation is diminishing educational diversity and taking agency away from teachers, making inspiring students a difficult task. In addition, the quality of teaching is judged heavily by testing which does not accurately reflect learning, stifles creativity and creates one-size-fits-all curriculums. 
                    </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive about_images" src="http://www.educationnews.org/wp-content/uploads/2012/02/teen_test_stress_exam.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Our solution</h2>
                    <p class="lead">Everyone has something they are passionate about and want to share. We believe that passion and enthusiasm are the most important ingredients in a teacher. We want to create a platform to leverage the infectious nature of passion by connecting enthusiastic individuals to encourage peer teaching and learning. Workshop is a site which will allow anyone to host a workshop about anything and open to all, supplementing existing curriculums by letting regular people cover less mainstream topics and skills, and encourage a habit of lifelong learning. </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive about_images" src="http://www.blacksheepknitting.com/wp-content/uploads/2011/07/Class32.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Our Vision</h2>
                    <p class="lead">We want to create a network and space for the motivated and the curious. We want to take self-help and learning out of e-learning sites and back in the hands of regular people, and inspire a lifelong desire to teach and learn. </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive about_images" src="http://beta.custompractice.co.uk/wp-content/uploads/2010/10/Custom-Practice-Classical-Acting-Workshop-004.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <!-- /.banner -->